<?php
// @codingStandardsIgnoreFile
/**
 * Generated frontend static JavaScript data map for s2Member Framework.
 *
 * Generated: 2026-09-13 06:17 UTC (260913.0617)
 *
 * Generated from paired data-boundary markers in the canonical frontend JavaScript source files.
 * Do not edit this file by hand; the project build regenerates it from the canonical JavaScript source.
 *
 * @package s2Member\CSS_JS
 * @since 260906.0738
 */
if(!defined('ABSPATH'))
	exit;

//260906.1530 Evaluate all values by default; an optional key set can restrict evaluation to selected stable slots.
$s2_data_keys = (isset($s2_data_keys) && is_array($s2_data_keys)) ? $s2_data_keys : NULL;
$data = array();

if($s2_data_keys === NULL || isset($s2_data_keys[0]))
	$data[0] = /*d*/ c_ws_plugin__s2member_utils_conds::bp_is_installed("query-active-plugins") ? "1" : "" /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[1]))
	$data[1] = /*d*/ c_ws_plugin__s2member_utils_dirs::basename_dir_app_data($GLOBALS["WS_PLUGIN__"]["s2member"]["c"]["files_dir"]) /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[2]))
	$data[2] = /*d*/ c_ws_plugin__s2member_user_securities::min_password_length() /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[3]))
	$data[3] = /*d*/ c_ws_plugin__s2member_user_securities::min_password_strength_code() /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[4]))
	$data[4] = /*d*/ c_ws_plugin__s2member_user_securities::min_password_strength_label() /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[5]))
	$data[5] = /*d*/ c_ws_plugin__s2member_user_securities::min_password_strength_score() /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[6]))
	$data[6] = /*d*/ _x("Strength indicator", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[7]))
	$data[7] = /*d*/ _x("Very weak", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[8]))
	$data[8] = /*d*/ _x("Weak", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[9]))
	$data[9] = /*d*/ _x("Good", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[10]))
	$data[10] = /*d*/ _x("Strong", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[11]))
	$data[11] = /*d*/ _x("Mismatch", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[12]))
	$data[12] = /*d*/ strlen($GLOBALS["WS_PLUGIN__"]["s2member"]["o"]["custom_reg_force_personal_emails"]) /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[13]))
	$data[13] = /*d*/ implode ("|", preg_split ("/[\r\n\t ;,]+/", preg_quote ($GLOBALS["WS_PLUGIN__"]["s2member"]["o"]["custom_reg_force_personal_emails"], "/"))) /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[14]))
	$data[14] = /*d*/ _x("Please check at least one of the boxes.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[15]))
	$data[15] = /*d*/ _x("Required. This box must be checked.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[16]))
	$data[16] = /*d*/ _x("Please select one of the options.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[17]))
	$data[17] = /*d*/ _x("Please select at least one of the options.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[18]))
	$data[18] = /*d*/ _x("This is a required field, please try again.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[19]))
	$data[19] = /*d*/ _x("Must be numeric (with or without decimals, commas allowed).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[20]))
	$data[20] = /*d*/ _x("Must be numeric (with or without decimals, no commas).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[21]))
	$data[21] = /*d*/ _x("Must be an integer (a whole number, without any decimals).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[22]))
	$data[22] = /*d*/ _x("Must be an integer > 0 (whole number, no decimals, greater than 0).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[23]))
	$data[23] = /*d*/ _x("Must be a float (floating point number, decimals required).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[24]))
	$data[24] = /*d*/ _x("Must be a float > 0 (floating point number, decimals required, greater than 0).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[25]))
	$data[25] = /*d*/ _x("Must be a date (required date format: dd/mm/yyyy).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[26]))
	$data[26] = /*d*/ _x("Must be a valid email address.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[27]))
	$data[27] = /*d*/ _x("Please use a personal email address.\nAddresses like <%s@> are problematic.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[28]))
	$data[28] = /*d*/ _x("Must be a full URL (starting with http or https).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[29]))
	$data[29] = /*d*/ _x("Must be a domain name (domain name only, without http).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[30]))
	$data[30] = /*d*/ _x("Must be a phone # (10 digits w/possible hyphens, spaces, brackets).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[31]))
	$data[31] = /*d*/ _x("Must be a US zipcode (5-9 digits w/ possible hyphen).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[32]))
	$data[32] = /*d*/ _x("Must be a Canadian zipcode (6 alpha-numerics w/possible space).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[33]))
	$data[33] = /*d*/ _x("Must be a zipcode (either a US or Canadian zipcode).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[34]))
	$data[34] = /*d*/ _x("Must be a valid UK postcode.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[35]))
	$data[35] = /*d*/ _x("Please use alphanumerics, spaces & punctuation only.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[36]))
	$data[36] = /*d*/ _x("Please use alphanumerics & spaces only.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[37]))
	$data[37] = /*d*/ _x("Please use alphanumerics & punctuation only (no spaces).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[38]))
	$data[38] = /*d*/ _x("Please use alphanumerics only (no spaces/punctuation).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[39]))
	$data[39] = /*d*/ _x("Please use alphabetics only (no digits/spaces/punctuation).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[40]))
	$data[40] = /*d*/ _x("Please use numeric digits only.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[41]))
	$data[41] = /*d*/ _x("Must be exactly %s %s.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[42]))
	$data[42] = /*d*/ _x("digit", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[43]))
	$data[43] = /*d*/ _x("digits", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[44]))
	$data[44] = /*d*/ _x("character", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[45]))
	$data[45] = /*d*/ _x("characters", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[46]))
	$data[46] = /*d*/ _x("Must be at least %s %s.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[47]))
	$data[47] = /*d*/ _x("— Confirm File Download —", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[48]))
	$data[48] = /*d*/ _x("You`ve downloaded %s protected %s in the last %s.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[49]))
	$data[49] = /*d*/ _x("file", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[50]))
	$data[50] = /*d*/ _x("files", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[51]))
	$data[51] = /*d*/ _x("24 hours", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[52]))
	$data[52] = /*d*/ _x("%s days", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[53]))
	$data[53] = /*d*/ _x("You`re entitled to UNLIMITED downloads though (so, no worries).", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[54]))
	$data[54] = /*d*/ _x("You`re entitled to %s unique %s %s.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[55]))
	$data[55] = /*d*/ _x("download", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[56]))
	$data[56] = /*d*/ _x("downloads", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[57]))
	$data[57] = /*d*/ _x("each day", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[58]))
	$data[58] = /*d*/ _x("every %s-day period", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[59]))
	$data[59] = /*d*/ _x("— Oops, you missed something: —", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[60]))
	$data[60] = /*d*/ _x("Passwords do not match up. Please try again.", "s2member-front", "s2member") /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[61]))
	$data[61] = /*d*/ sprintf(_x("Password MUST be at least %s characters. Please try again.", "s2member-front", "s2member"), c_ws_plugin__s2member_user_securities::min_password_length()) /*b*/;
if($s2_data_keys === NULL || isset($s2_data_keys[62]))
	$data[62] = /*d*/ sprintf(_x("Password strength MUST be %s. Please try again.", "s2member-front", "s2member"), c_ws_plugin__s2member_user_securities::min_password_strength_label()) /*b*/;

return $data;
