<?php
//260906.1654 Regenerate the shipped static JavaScript data map from the canonical marked expressions.

function s2member_build_static_js_data_map_fail($message)
{
	fwrite(STDERR, "Static JavaScript data-map build failed: ".$message."\n");
	exit(1);
}

function s2member_build_static_js_data_map_normalize_expression($expression)
{
	$tokens = token_get_all('<?php '.$expression.';');
	$normalized = '';
	foreach($tokens as $token)
	{
		if(is_array($token))
		{
			if(in_array($token[0], array(T_OPEN_TAG, T_WHITESPACE, T_COMMENT, T_DOC_COMMENT), TRUE))
				continue;
			$normalized .= $token[1];
		}
		else
			$normalized .= $token;
	}
	return $normalized;
}

function s2member_build_static_js_data_map_expressions($source_files)
{
	$expressions = array();
	$slot_by_expression = array();
	$expression_by_normalized = array();

	foreach($source_files as $source_file)
	{
		if(!is_readable($source_file) || ($source = file_get_contents($source_file)) === FALSE)
			s2member_build_static_js_data_map_fail('Unable to read source file: '.$source_file);

		$php_blocks = array();
		preg_match_all('/<\?php.*?\?>/s', $source, $php_blocks);
		$php_blocks = isset($php_blocks[0]) ? $php_blocks[0] : array();

		foreach($php_blocks as $php_block)
		{
			if(substr_count($php_block, '/*d*/') !== 1 || substr_count($php_block, '/*b*/') !== 1
			   || !preg_match('/\/\*d\*\/(.*?)\/\*b\*\//s', $php_block, $match))
				s2member_build_static_js_data_map_fail('Every PHP interpolation must contain exactly one paired /*d*/ ... /*b*/ expression in: '.$source_file);

			$expression = trim((string)$match[1]);
			if($expression === '')
				s2member_build_static_js_data_map_fail('A marked expression is empty in: '.$source_file);

			if(isset($slot_by_expression[$expression]))
				continue;

			$normalized = s2member_build_static_js_data_map_normalize_expression($expression);
			if(isset($expression_by_normalized[$normalized]) && $expression_by_normalized[$normalized] !== $expression)
				s2member_build_static_js_data_map_fail('Equivalent expressions differ only by PHP whitespace/comments. Normalize the canonical JavaScript source before building: '.$expression);

			$slot_by_expression[$expression] = count($expressions);
			$expression_by_normalized[$normalized] = $expression;
			$expressions[] = $expression;
		}
	}
	if(!$expressions)
		s2member_build_static_js_data_map_fail('No marked JavaScript data expressions were found.');
	return $expressions;
}

function s2member_build_static_js_data_map_write($output_file, $contents)
{
	$current = is_readable($output_file) ? file_get_contents($output_file) : FALSE;
	$current_for_compare = ($current !== FALSE) ? preg_replace('/^ \* Generated: \d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC \(\d{6}\.\d{4}\)$/m', ' * Generated: @@GENERATED@@', $current, 1) : FALSE;
	if($current_for_compare === $contents)
	{
		echo "Static JavaScript data map is current: ".$output_file."\n";
		return;
	}

	$generated = gmdate('Y-m-d H:i').' UTC ('.gmdate('ymd.Hi').')';
	$contents = str_replace('@@GENERATED@@', $generated, $contents);
	$temp_file = $output_file.'.tmp-'.getmypid();
	if(file_put_contents($temp_file, $contents) !== strlen($contents) || !rename($temp_file, $output_file))
	{
		@unlink($temp_file);
		s2member_build_static_js_data_map_fail('Unable to write generated data map: '.$output_file);
	}
	echo "Regenerated static JavaScript data map: ".$output_file."\n";
}

$base_dir = __DIR__;
$expressions = s2member_build_static_js_data_map_expressions(array(
	$base_dir.'/src/includes/s2member.js',
));
$output_file = $base_dir.'/src/includes/s2member.js.php';

$contents = <<<'PHP'
<?php
// @codingStandardsIgnoreFile
/**
 * Generated frontend static JavaScript data map for s2Member Framework.
 *
 * Generated: @@GENERATED@@
 *
 * Generated from paired data-boundary markers in the canonical frontend JavaScript source files.
 * Do not edit this file by hand; the project build regenerates it from the canonical JavaScript source.
 *
 * @package s2Member\CSS_JS
 * @since 260906.0738
 */
if(!defined('ABSPATH'))
	exit;

//260906.1530 Evaluate all values by default; an optional key set can restrict evaluation to selected stable slots.
$s2_data_keys = (isset($s2_data_keys) && is_array($s2_data_keys)) ? $s2_data_keys : NULL;
$data = array();

PHP;

$contents .= "\n";
foreach($expressions as $slot => $expression)
{
	$contents .= 'if($s2_data_keys === NULL || isset($s2_data_keys['.$slot.']))'."\n";
	$contents .= "\t".'$data['.$slot.'] = /*d*/ '.$expression.' /*b*/;'."\n";
}
$contents .= "\nreturn \$data;\n";

s2member_build_static_js_data_map_write($output_file, $contents);
